vim.fn.setenv("OPENAI_API_KEY", "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")
require("cytommi.cmp")
require("cytommi.colorscheme")
require("cytommi.copilot")
require("cytommi.harpoon")
require("cytommi.keymaps")
require("cytommi.lsp")
require("cytommi.lualine")
require("cytommi.null-ls")
require("cytommi.nvim-tree")
require("cytommi.nvim-web-devicons")
require("cytommi.options")
require("cytommi.plugins")
require("cytommi.rhubarb")
require("cytommi.telescope")
require("cytommi.treesitter")
require("cytommi.worktree")
