vim.cmd([[packadd packer.nvim]])
vim.fn.setenv("OPENAI_API_KEY", "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")

require("cytommi.plugins")
require("cytommi.cmp")
require("cytommi.colorscheme")
require("cytommi.copilot")
require("cytommi.harpoon")
require("cytommi.keymaps")
require("cytommi.lsp")
require("cytommi.lualine")
require("cytommi.null-ls")
require("cytommi.nvim-tree")
require("cytommi.nvim-web-devicons")
require("cytommi.options")
require("cytommi.rhubarb")
require("cytommi.telescope")
require("cytommi.treesitter")
require("cytommi.worktree")
